/**
 * ECOMART — Product Catalog & Sustainability Data Store
 * All 12 sustainable products with realistic eco-scores, metrics, and lifecycle attributes.
 */

const ECOMART_PRODUCTS = [
  {
    id: 'prod-01',
    name: 'Bamboo Toothbrush',
    price: 6,
    rating: 5,
    category: 'Personal Care',
    image: 'assets/images/bamboo_toothbrush.jpg',
    tagline: '100% Biodegradable Moso Bamboo & Castor Bio-Bristles',
    description: 'Ergonomically sculpted from organically cultivated Moso bamboo. The charcoal-infused bio-bristles are derived from castor bean oil, offering superior plaque removal while keeping 4.5 billion plastic toothbrushes out of oceans and landfills annually.',
    sustainabilityScore: 98,
    co2Saved: '1.2 kg',
    wasteDiverted: '0.15 kg plastic',
    replaces: '4 plastic toothbrushes/yr',
    materials: ['Organically Grown Moso Bamboo', 'Castor Bean Oil Bio-Bristles', 'Non-Toxic Plant Resin'],
    packaging: '100% Unbleached Kraft Paper (Compostable)',
    origin: 'Anji Eco-Forestry Collective',
    certifications: ['FSC Certified', 'USDA Biobased 100%', 'Cruelty-Free'],
    isFeatured: true,
    editorQuote: 'The gold standard of zero-waste oral hygiene. Flawlessly balanced and completely compostable.'
  },
  {
    id: 'prod-02',
    name: 'Insulated Steel Bottle',
    price: 24,
    rating: 5,
    category: 'Drinkware',
    image: 'assets/images/insulated_steel_bottle.jpg',
    tagline: 'Triple-Wall Vacuum 18/8 Pro-Grade Stainless Steel',
    description: 'Engineered for extreme durability and thermal excellence. Keeps liquids chilled for 24 hours or piping hot for 12 hours with zero condensation. Laser-etched with the signature Ecomart botanical emblem and guaranteed for over a decade of daily swaps.',
    sustainabilityScore: 99,
    co2Saved: '18.4 kg',
    wasteDiverted: '150 single-use bottles/yr',
    replaces: '150+ plastic bottles/year',
    materials: ['18/8 Pro-Grade Recycled Steel', 'Food-Grade Silicone Seal', 'BPA-Free Recycled Cap'],
    packaging: 'Mushroom Mycelium Foam & Recycled Box',
    origin: 'Carbon-Neutral Hydro-Powered Facility',
    certifications: ['B-Corp Verified', 'Climate Neutral', 'FDA Food Grade'],
    isFeatured: true,
    editorQuote: 'Our flagship eco-vessel. Built like a spacecraft, designed for a lifetime of zero single-use waste.'
  },
  {
    id: 'prod-03',
    name: 'Organic Cotton Tote',
    price: 18,
    rating: 4,
    category: 'Fashion',
    image: 'assets/images/organic_cotton_tote.jpg',
    tagline: 'GOTS-Certified Heavyweight Raw Cotton Canvas',
    description: 'Handcrafted from 10oz unbleached organic cotton with reinforced cross-stitched handles capable of carrying up to 25kg. Replaces hundreds of flimsy plastic grocery bags with timeless minimalist editorial aesthetics.',
    sustainabilityScore: 92,
    co2Saved: '4.8 kg',
    wasteDiverted: '400+ plastic bags',
    replaces: '400+ single-use shopping bags',
    materials: ['100% GOTS Certified Organic Cotton', 'Water-Based Botanical Inks', 'Zero Synthetic Dyes'],
    packaging: 'Roll-tied with natural jute twine',
    origin: 'Fair-Trade Certified Women Artisan Cooperative',
    certifications: ['GOTS Certified', 'Fair Trade', 'OEKO-TEX Standard 100'],
    isFeatured: false,
    editorQuote: 'Indestructible daily carry. Thick organic weave that ages beautifully with every trip.'
  },
  {
    id: 'prod-04',
    name: 'Recycled Ocean Bottle',
    price: 28,
    rating: 5,
    category: 'Drinkware',
    image: 'assets/images/recycled_ocean_bottle.jpg',
    tagline: '100% Ocean-Bound Upcycled Polymers & Brushed Steel',
    description: 'Each bottle funds the recovery of 1,000 ocean-bound plastic bottles in coastal communities. Features a dual-opening leakproof lid for ice cubes and easy cleaning, NFC impact tracking smart chip, and double thermal insulation.',
    sustainabilityScore: 97,
    co2Saved: '22.1 kg',
    wasteDiverted: '1,000 ocean bottles collected',
    replaces: '200 single-use drink containers',
    materials: ['Upcycled Ocean-Bound RPET', 'Recycled Stainless Steel', 'Silicone Gasket'],
    packaging: '100% Recycled Cardboard Cylinder',
    origin: 'Coastal Circularity Alliance',
    certifications: ['Ocean Plastic Verified', 'B-Corp Certified', 'Carbon Neutral'],
    isFeatured: true,
    editorQuote: 'High-tech meets restorative ecology. Every sip funds direct marine cleanup.'
  },
  {
    id: 'prod-05',
    name: 'Plant-Based Cleaning Kit',
    price: 32,
    rating: 5,
    category: 'Cleaning',
    image: 'assets/images/plant_based_cleaning_kit.jpg',
    tagline: 'Refillable Amber Glass & Concentrated Soluble Tablets',
    description: 'Eliminate shipping heavy water and single-use cleaning bottles forever. Just drop a concentrated plant-powered tablet into the forever amber glass spray bottle, add tap water, and enjoy non-toxic, powerful multi-surface botanical cleaning.',
    sustainabilityScore: 96,
    co2Saved: '9.6 kg',
    wasteDiverted: '12 plastic spray bottles',
    replaces: '12 single-use chemical cleaners/yr',
    materials: ['Heavyweight Amber Glass', 'Coconut-Derived Surfactants', 'Pure Essential Oils'],
    packaging: 'Compostable Glassine Pods & Kraft Box',
    origin: 'Solar-Powered Eco Laboratory',
    certifications: ['Leaping Bunny', 'EPA Safer Choice', 'Zero Microplastics'],
    isFeatured: true,
    editorQuote: 'Revolutionary clean chemistry. Replaces an entire cabinet of toxic plastic sprays.'
  },
  {
    id: 'prod-06',
    name: 'Cold-Pressed Soap Bar',
    price: 8,
    rating: 4,
    category: 'Personal Care',
    image: 'assets/images/cold_pressed_soap_bar.jpg',
    tagline: 'Organic Olive Oil, Shea Butter & Crushed Eucalyptus',
    description: 'Artisan cold-cured over six weeks in small batches to preserve natural botanical glycerin. Infused with eucalyptus, tea tree, and crushed French green clay for deep cellular nourishment with zero palm oil or artificial fragrances.',
    sustainabilityScore: 94,
    co2Saved: '2.1 kg',
    wasteDiverted: '3 plastic shower gel bottles',
    replaces: '3 liquid body wash bottles',
    materials: ['Cold-Pressed Olive Oil', 'Wild-Harvested Shea Butter', 'Eucalyptus Botanicals'],
    packaging: 'Plantable Seed Paper Wrap',
    origin: 'Provence Herbal Farm Sanctuary',
    certifications: ['Palm Oil Free', 'Cruelty-Free Vegan', 'Soil Association Organic'],
    isFeatured: false,
    editorQuote: 'Sensory luxury meets zero-waste hygiene. The wrapper grows wildflowers when planted.'
  },
  {
    id: 'prod-07',
    name: 'Recycled Paper Notebook',
    price: 14,
    rating: 4,
    category: 'Stationery',
    image: 'assets/images/recycled_paper_notebook.jpg',
    tagline: '100% Post-Consumer Acid-Free Paper & Wheat-Straw Hardcover',
    description: '192 dot-grid pages made entirely from recycled post-consumer office paper, bound with lay-flat thread and a resilient wheat-straw board cover. Bleed-proof for fountain pens with a debossed cyber-neon leaf insignia.',
    sustainabilityScore: 91,
    co2Saved: '3.4 kg',
    wasteDiverted: '0.8 kg post-consumer pulp',
    replaces: 'Standard virgin tree paper notebooks',
    materials: ['100% Post-Consumer Recycled Paper', 'Upcycled Wheat Straw Board', 'Soy Ink Binding'],
    packaging: 'Zero packaging (Naked Book design)',
    origin: 'Closed-Loop Circular Mill',
    certifications: ['FSC Recycled 100%', 'Acid-Free Archival', 'Chlorine-Free'],
    isFeatured: false,
    editorQuote: 'Silky smooth archival paper created entirely from reclaimed urban waste.'
  },
  {
    id: 'prod-08',
    name: 'Sustainable Sneakers',
    price: 89,
    rating: 5,
    category: 'Fashion',
    image: 'assets/images/sustainable_sneakers.jpg',
    tagline: 'Eucalyptus Fibers & Sugarcane SweetFoam® Outsole',
    description: 'Ultra-breathable, silky-soft knit uppers spun from sustainably managed eucalyptus tree fiber. Features a shock-absorbing midsole derived from Brazilian sugarcane and glowing neon accents crafted from reclaimed ocean polymers.',
    sustainabilityScore: 99,
    co2Saved: '14.2 kg',
    wasteDiverted: '2.5 kg virgin synthetic rubber',
    replaces: 'Petroleum-based synthetic trainers',
    materials: ['FSC Eucalyptus Tree Fiber', 'Sugarcane SweetFoam®', 'Recycled PET Laces'],
    packaging: '100% Recycled Shoebox & Bio-Film',
    origin: 'Ethical Zero-Emission Footwear Guild',
    certifications: ['B-Corp Certified', 'Carbon Neutral Footprint', 'PETA Vegan'],
    isFeatured: true,
    editorQuote: 'The peak of futuristic footwear engineering. Insanely comfortable and remarkably carbon-negative.'
  },
  {
    id: 'prod-09',
    name: 'Solar Power Band',
    price: 45,
    rating: 5,
    category: 'Solar',
    image: 'assets/images/solar_power_band.jpg',
    tagline: 'Flexible Monocrystalline Wristband with 5000mAh Reserve',
    description: 'Wearable high-efficiency solar kinetic harvesting wristband. Integrates flexible micro-photovoltaic cells that continuously harvest ambient sunlight to power your smart devices on the move with cyber-green HUD LED battery telemetry.',
    sustainabilityScore: 97,
    co2Saved: '8.7 kg',
    wasteDiverted: '100+ disposable AA batteries',
    replaces: 'Frequent wall grid charging & alkaline cells',
    materials: ['Flexible Monocrystalline PV', 'Recycled Ocean Polymer Strap', 'Non-Toxic Solid-State Battery'],
    packaging: 'Molded Bamboo Fiber Shell',
    origin: 'Advanced Clean-Tech Foundry',
    certifications: ['RoHS Compliant', 'CE Clean Energy', 'Conflict-Free Minerals'],
    isFeatured: true,
    editorQuote: 'Wearable infinite energy. Turns natural sunlight into instant device power anywhere on Earth.'
  },
  {
    id: 'prod-10',
    name: 'Solar Lantern',
    price: 36,
    rating: 5,
    category: 'Outdoor',
    image: 'assets/images/solar_lantern.jpg',
    tagline: 'Collapsible Waterproof Solar LED with 75-Lumen Ambient Glow',
    description: 'Inflatable, waterproof (IP67), and featherlight collapsible solar lantern. Charges in 7 hours of direct sunlight to deliver up to 24 hours of warm LED ambient lighting for campsites, off-grid cabins, or emergency cyber readiness.',
    sustainabilityScore: 98,
    co2Saved: '11.5 kg',
    wasteDiverted: '40+ kerosene lanterns / batteries',
    replaces: 'Fossil fuel lantern fuel & disposable batteries',
    materials: ['Heavy-Duty Recycled TPU', 'Integrated Solar PV Cell', 'High-Efficiency Low-Draw LEDs'],
    packaging: 'Minimal Flat-Pack Recycled Cardboard',
    origin: 'Clean Light Off-Grid Initiative',
    certifications: ['IP67 Waterproof', '1% For The Planet', 'Zero Hazardous Waste'],
    isFeatured: false,
    editorQuote: 'Packs flat as a notebook, lights up an entire campsite with pure harvested sunshine.'
  },
  {
    id: 'prod-11',
    name: 'Beeswax Foot Balm',
    price: 12,
    rating: 4,
    category: 'Wellness',
    image: 'assets/images/beeswax_foot_balm.jpg',
    tagline: 'Ethically Foraged Wild Beeswax, Peppermint & Calendula',
    description: 'Deeply restorative intense moisturizing balm formulated with pesticide-free wild beeswax, organic coconut oil, calendula extract, and soothing peppermint. Packaged in a reusable amber glass pot with zero microplastics or parabens.',
    sustainabilityScore: 93,
    co2Saved: '1.8 kg',
    wasteDiverted: '4 plastic lotion tubes',
    replaces: 'Synthetic petroleum jelly & plastic lotions',
    materials: ['Ethically Sourced Raw Beeswax', 'Organic Calendula Herbal Oil', 'Arnica & Peppermint Extract'],
    packaging: 'Heavyweight UV-Protected Amber Glass Pot',
    origin: 'Regenerative Apiculture Sanctuary',
    certifications: ['Cruelty Free', 'Organic Wildcraft', 'Zero Microplastics'],
    isFeatured: false,
    editorQuote: 'Intensive botanical recovery for active feet. Pure nourishment directly from ethical hives.'
  },
  {
    id: 'prod-12',
    name: 'Bamboo Cutlery Set',
    price: 16,
    rating: 5,
    category: 'Kitchen',
    image: 'assets/images/bamboo_cutlery_set.jpg',
    tagline: 'Travel Fork, Knife, Spoon, Chopsticks & Straw in Canvas Roll',
    description: 'The definitive on-the-go zero waste dining companion. Hand-finished organic bamboo utensils including fork, serrated knife, deep soup spoon, chopsticks, and straw with cleaning brush, rolled into an unbleached organic canvas travel case.',
    sustainabilityScore: 98,
    co2Saved: '7.3 kg',
    wasteDiverted: '500+ single-use plastic cutlery pieces',
    replaces: '500+ disposable plastic forks & straws',
    materials: ['Organic Moso Bamboo', 'Natural Food-Safe Carnauba Wax Finish', 'Organic Cotton Canvas Pouch'],
    packaging: '100% Recycled Paper Sleeve',
    origin: 'Sustainable Woodcraft Guild',
    certifications: ['Food Safe Grade A', 'FSC 100% Bamboo', 'Compostable'],
    isFeatured: true,
    editorQuote: 'Never accept single-use plastic cutlery again. Lightweight, compact, and built to travel.'
  }
];

const SUSTAINABILITY_PRINCIPLES = [
  {
    id: 'materials',
    title: 'Responsible Materials',
    subtitle: '100% Bio-Based, Upcycled, or Closed-Loop Recycled',
    icon: 'leaf',
    content: 'We rigorously audit the molecular origin of every raw component. Virgin petroleum plastics are strictly prohibited across our marketplace. All polymers must be certified ocean-recovered or post-consumer upcycled. Organics (cotton, bamboo, hemp, beeswax) must hold GOTS, FSC, or regenerative agroforestry certifications with zero pesticide exposure.'
  },
  {
    id: 'packaging',
    title: 'Plastic-Free Packaging',
    subtitle: 'Compostable, Mushroom Mycelium & Water-Activated Sealing',
    icon: 'box',
    content: 'Packaging is designed to return to the earth without leaving chemical traces. We utilize agricultural byproduct cardstock, water-activated kraft paper tape, plantable wildflower seed paper wraps, and biodegradable mushroom mycelium foam. 100% of our shipment boxes are naturally backyard compostable within 90 days.'
  },
  {
    id: 'manufacturing',
    title: 'Clean Manufacturing & Fair Ethics',
    subtitle: 'Renewable-Powered Facilities & Certified Living Wages',
    icon: 'zap',
    content: 'Every manufacturing partner in the Ecomart network operates under strict environmental charters. Facilities must harness renewable solar, wind, or hydro power, implement closed-loop water recirculation systems, and maintain certified fair living wages for all craftspeople and workers with zero hazardous factory discharge.'
  },
  {
    id: 'longevity',
    title: 'Engineered Longevity',
    subtitle: 'Built for Decades of Daily Swaps, Not Planned Obsolescence',
    icon: 'shield',
    content: 'True sustainability is using an item thousands of times. We prioritize modular repairability, replacement gaskets, reinforced cross-stitching, and pro-grade materials like 18/8 stainless steel and seasoned bamboo. If a product fails within 3 years of regular use, our Swap & Repair program provides free component replacement.'
  },
  {
    id: 'circularity',
    title: 'End of Life Circularity',
    subtitle: 'Zero Landfill Commitment & Closed-Loop Takeback Guild',
    icon: 'refresh',
    content: 'Every product on Ecomart features a designated circular pathway. When your product reaches the end of its useful lifespan decades down the road, it can be composted in natural soil or mailed back through our prepaid Takeback Guild for high-grade thermal upcycling and raw material recovery.'
  }
];

const IMPACT_METRICS = {
  co2SavedKg: 24580,
  bottlesAvoided: 18420,
  wasteDivertedKg: 7250,
  ecoRouteCoverage: 92,
  swapsCompleted: 48920,
  treesPlanted: 14600
};
